http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
    www-to-non-www-redirect:
      redirectregex:
        permanent: true
        regex: "^https?://www\\.(.+)"
        replacement: "https://${1}"
    cache-headers:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=31536000"
    traefik-compress:
      compress: {}
    secure-headers:
      headers:
        frameDeny: true
        browserXssFilter: true